import { PostgreSql } from "ts-sql-query/databases/PostgreSql";
import { SelectValues } from "ts-sql-query/expressions/select";
import { PgPoolQueryRunner } from "ts-sql-query/queryRunners/PgPoolQueryRunner";
import { Table } from "ts-sql-query/Table";
import { dbPool } from "../../db/src/run_on_pool";
import { DBConnection, MyDb } from "./db";

class KursTable extends Table<MyDb> {
  id = this.autogeneratedPrimaryKey("id", "int");
  leiterId = this.column("leiter_id", "int");
  beginn = this.column("beginn", "localDate");
  constructor() {
    super("kurs");
  }
}

const kursTableInstance = new KursTable();

export interface Kurs {
  id: number;
  leiterId: number;
  beginn: Date
}

const selectKurs: SelectValues<MyDb & PostgreSql, KursTable, Kurs> = {
  id: kursTableInstance.id,
  leiterId: kursTableInstance.leiterId,
  beginn: kursTableInstance.beginn,
};

export class KursDto {
  private static getConnection(): DBConnection {
    return new DBConnection(new PgPoolQueryRunner(dbPool));
  }

  public static findById(id: number): Promise<Kurs> {
    return this.getConnection()
      .selectFrom(kursTableInstance)
      .where(kursTableInstance.id.equals(id))
      .select(selectKurs)
      .executeSelectOne();
  }

  public static findAll(): Promise<Kurs[]> {
    return this.getConnection()
      .selectFrom(kursTableInstance)
      .select(selectKurs)
      .executeSelectMany();
  }

  public static insert(kurs: Kurs): Promise<Kurs["id"]> {
    return this.getConnection()
      .insertInto(kursTableInstance)
      .values(kurs)
      .returningLastInsertedId()
      .executeInsert();
  }
}
