import { asInt } from "ts-extended-types";
import { PostgreSql } from "ts-sql-query/databases/PostgreSql";
import { SelectValues } from "ts-sql-query/expressions/select";
import { PgPoolQueryRunner } from "ts-sql-query/queryRunners/PgPoolQueryRunner";
import { dbPool } from "../../db/src/run_on_pool";
import { DBConnection, DbInsertSets, DbSelectValues, DbTable, MyDb } from "./db";

class LandesverbandTable extends DbTable {
  id = this.autogeneratedPrimaryKey("id", "int");
  name = this.column("name", "string");
  constructor() {
    super("landesverband");
  }
}

export const landesverbandTableInstance = new LandesverbandTable();

export interface Landesverband {
  id: number;
  name: string;
}

const selectLandesverband:  DbSelectValues<
  LandesverbandTable,
  Landesverband
> = {
  id: landesverbandTableInstance.id,
  name: landesverbandTableInstance.name,
};

function adaptLandesverbandToDb(
  landesverband: Landesverband
): DbInsertSets<LandesverbandTable> {
  return {
    id: asInt(landesverband.id),
    name: landesverband.name,
  };
}

export class LandesverbandDto {
  private static getConnection(): DBConnection {
    return new DBConnection(new PgPoolQueryRunner(dbPool));
  }

  public static findById(id: number): Promise<Landesverband> {
    return this.getConnection()
      .selectFrom(landesverbandTableInstance)
      .where(landesverbandTableInstance.id.equals(asInt(id)))
      .select(selectLandesverband)
      .executeSelectOne();
  }

  public static findAll(): Promise<Landesverband[]> {
    return this.getConnection()
      .selectFrom(landesverbandTableInstance)
      .select(selectLandesverband)
      .executeSelectMany();
  }

  public static insert(
    landesverband: Landesverband
  ): Promise<Landesverband["id"]> {
    return this.getConnection()
      .insertInto(landesverbandTableInstance)
      .values(adaptLandesverbandToDb(landesverband))
      .returningLastInsertedId()
      .executeInsert();
  }
}
